# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Or Polaczek
description: "A personal homepage & tech blog by Or Polaczek"
keywords: "Research,VoIP,Asterisk,Selenium,Apple,HomeKit,Mobile,SDKs,Python"
url: https://orpolaczek.github.io
baseurl: "/techblog"

google_analytics: UA-103804205-1
repo: https://github.com/orpolaczek
disqus_shortname: "thoughts-about-tech"
disqus_site_shortname: "thoughts-about-tech"

# Author settings
author:
  name: Or Polaczek
  job: Research Engineer
  bio: "I'm a tech enthusiast, I love solving complexed problems <br/>
  and sharing knowledge. This is my homepage :)"
  thumb: /images/author.png
  email: or@polaczek.co.il
  url: https://orpolaczek.github.io/
  github: https://github.com/orpolaczek
  twitter: https://twitter.com/orpolaczek
  #facebook: https://facebook.com/po
  linkedin: https://linkedin.com/in/orpolaczek

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: projects
    title: Projects
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
